countdown-seconds: 10
respawn-seconds: 5
ending-seconds: 8
modes:
  solo:
    minimum-players: 2
  doubles:
    minimum-players: 2
lobby:
  teleport-on-join: true
setup:
  auto-open-on-game-world-teleport: true
isolation:
  enabled: true
  chat: true
chat:
  lobby-prefix: "&7[LOBBY] "
  name-suffix: " &8> &f"
  team-prefixes:
    red: "&c[RED] "
    blue: "&9[BLUE] "
    green: "&a[GREEN] "
    yellow: "&e[YELLOW] "
scoreboard:
  footer: "&eplay.bedlam"
  lobby-id: "L1"
void-drop-blocks: 30
generator-periods:
  iron: 20
  gold: 80
  diamond: 600
  emerald: 1200
generator-upgrades:
  diamond:
    tier-2-seconds: 360
    tier-3-seconds: 720
    tier-2-period: 460
    tier-3-period: 240
  emerald:
    tier-2-seconds: 720
    tier-3-seconds: 1080
    tier-2-period: 900
    tier-3-period: 600
